---
title: "Simulación ARMA y ACF Teórica"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simulación y ACF

Vamos a simular un proceso $\{X_{t}\}\sim$ IID

```{r SimulIID}
n=200 #Tamaño de la serie
l=50 #condiciones iniciales
theta=-0.5 
phi=0.5
sigma=2
###Simulación IID####
serieIID=as.ts(rnorm(n,0,2))
plot(serieIID,main='IID')
acf(serieIID)
```

```{r MA1}
#####Simulación MA(1)#####
ruido=rnorm(n+l,0,sigma)
MA1aux=rep(0,n+l)
MA1aux
for(j in 2:(n+l))
{
  MA1aux[j]=theta*ruido[j-1]+ruido[j]
}
MA1=as.ts(MA1aux[l+1:n])
plot(MA1)
acf(MA1)

```


## Simulación de procesos ARMA


```{r ARMA, echo=FALSE}
Tlength=200
arimaej=arima.sim(list(order = c(1,0,1),ar = c(0.7),ma=c(0.6)), n = Tlength)
plot(arimaej,main='ARMA(1,1)')
acf(arimaej,main='ACF muestral')

acf_ARMA<- ARMAacf(ar=c(0.8),ma=c(0.6), lag.max = 10)
lags <- 0:10 
plot(lags,acf_ARMA,xlim=c(1,10),ylab = "ACF",type="h",main = "ACF Teórica
     para ARMA(1,1)")
abline(h=0) #Agrega un eje al gráfico
```
```{r Comparar teóricas y muestrales}
Tlength = 200

# Simular ARMA(1,1)
arimaej = arima.sim(
  list(order = c(1,0,1),
       ar = 0.7,
       ma = 0.6),
  n = Tlength
)

# ACF muestral
acf_muestral = acf(arimaej, plot = FALSE)

# ACF teórica
acf_teorica = ARMAacf(ar = 0.7,
                      ma = 0.6,
                      lag.max = 10)

# Rezagos
lags = 0:10

# Gráfico base: ACF muestral
plot(lags,
     acf_muestral$acf[1:11],
     type = "h",
     lwd = 2,
     col = "black",
     ylim = c(min(acf_teorica,
                  acf_muestral$acf[1:11]),
              1),
     xlab = "Rezago",
     ylab = "ACF",
     main = "ACF muestral vs teórica")

# ACF teórica en rojo punteado
lines(lags,
      acf_teorica,
      col = "red",
      lty = 2,
      lwd = 2)

# Puntos sobre la línea teórica
points(lags,
       acf_teorica,
       col = "red",
       pch = 19)

abline(h = 0)

legend("topright",
       legend = c("Muestral", "Teórica"),
       col = c("black", "red"),
       lty = c(1,2),
       lwd = 2,
       pch = c(NA,19))
```



```{r ACFTeorica}
acf_ARMA<- ARMAacf(ar=c(0.0),ma=c(0.8,-0.6), lag.max = 10)
lags <- 0:10 
plot(lags,acf_ARMA,xlim=c(1,10),ylab = "ACF",type="h",main = "ACF para ARMA(1,1)")
abline(h=0) #Agrega un eje al gráfico
```

```{r}
library(UnitCircle)
UnitCircle::uc.check(c(1,0.2,0.7))
```


